### ISSUE TITLE
dwl: attachbottom.patch

### ISSUE THREAD

**Issue by fictitiousexistence** [AurelWeinhold/dwl#1]
Hi, I was wondering if you still use dwl and/or plan to update your attachbottom.patch for the latest 0.5 release?

Dwl got moved to [codeberg](https://codeberg.org/dwl/dwl) and your attachbottom.patch got put in the ["stale patches"](https://codeberg.org/dwl/dwl-patches/src/branch/main/_STALE_PATCHES)

If not, would you be opposed to someone updating the patch there?

Thanks.

**Comment by AurelWeinhold** [comment]
Hi, I am not using dwl anymore as it unfortunately broke for me and I needed a more stable system.

I would definitely not be opposed to someone else updating the patch! In fact I would be happy if it got used, so feel free!

Cheers.
